In [ ]:
import pandas as pd

In [ ]:
# file_path = 'Homework-DataFrame-Dataset.csv'  #update path if needed

# data = pd.read_csv('Homework-DataFrame-Dataset.csv', sep=';', on_bad_lines='skip')
# data.head()

tempat_file = 'Homework-DataFrame-Dataset.xlsx'
paid_transaction = pd.read_excel(tempat_file, sheet_name='Paid-Transaction')
seller = pd.read_excel(tempat_file, sheet_name='Seller')

seller.head()

      Order Number        Seller
0  201707209929420  Global Phone
1  201707129550097        E-shop
2  201707039056021   twelven com
3  201707099376522      GRAMEDIA
4  201707028956707        E-Bold

In [ ]:
#no1
paid_transaction['Full Name'] = (paid_transaction['First Name'] + '  ' + paid_transaction['Last Name']).str.title()

cols = paid_transaction.columns.tolist()
last_name_index = cols.index("Last Name")
cols.insert(last_name_index + 1, cols.pop(cols.index("Full Name")))
paid_transaction = paid_transaction[cols]

paid_transaction.head()

,Paid Date,Order Number,First Name,Last Name,Full Name,Meta Category,Product Name,Transaction Amount,Seller Discount,Sales Discount,Delivery Fee,Other Discount,GMV,Group
0,2017-07-24,201707240088517,elvride,aries,Elvride Aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,10200.0,9000,0.0,291000,NaN
1,2017-07-01,201707018889790,BASIR,Ninuk,Basir Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,0.0,0,0.0,287800,NaN
2,2017-07-07,201707079264675,Citra,Ardi,Citra Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,700.0,0,0.0,35000,NaN
3,2017-07-20,201707209945714,Dian,Renaldi,Dian Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,5900.0,0,0.0,85000,Group 1
4,2017-07-22,201707220002354,rizal,Tamba,Rizal Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,5600.0,0,0.0,81000,NaN

In [ ]:
#no2
paid_transaction['GMV'] = paid_transaction['Transaction Amount'] - paid_transaction ['Delivery Fee']
paid_transaction

,Paid Date,Order Number,First Name,Last Name,Full Name,Meta Category,Product Name,Transaction Amount,Seller Discount,Sales Discount,Delivery Fee,Other Discount,GMV,Group
0,2017-07-24,201707240088517,elvride,aries,Elvride Aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,10200.0,9000,0.0,291000,NaN
1,2017-07-01,201707018889790,BASIR,Ninuk,Basir Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,0.0,0,0.0,287800,NaN
2,2017-07-07,201707079264675,Citra,Ardi,Citra Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,700.0,0,0.0,35000,NaN
3,2017-07-20,201707209945714,Dian,Renaldi,Dian Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,5900.0,0,0.0,85000,Group 1
4,2017-07-22,201707220002354,rizal,Tamba,Rizal Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,5600.0,0,0.0,81000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,2017-12-01,201712012704898,Fitrah,gina,Fitrah Gina,Service/ Mokado,"Xtra Combo 12GB, 30hr",333000,300000,2300.0,0,0.0,333000,NaN
11996,2017-12-03,201712032723513,Djebeng,Shinta,Djebeng Shinta,Service/ Mokado,"Xtra Combo 12GB, 30hr",280000,222500,0.0,0,0.0,280000,NaN
11997,2017-12-04,201712042740205,Amik,Elan,Amik Elan,Home/ Food,Kreta - Kripik Tempe Indonesia - Rasa Jomblo d...,150000,81000,4800.0,0,0.0,150000,NaN
11998,2017-12-07,201712072778621,Anna,asih,Anna Asih,Gadget/ Komputer,Samsung Galaxy J5 Pro Garansi Resmi Special Price,475000,400000,0.0,0,0.0,475000,NaN
11999,2017-12-05,201712052746101,nidyah,ayi,Nidyah Ayi,Service/ Mokado,[SERBU 11.12] Share Tea Cocoa Rocksalt & Chees...,475000,400000,20000.0,17000,0.0,458000,NaN

In [ ]:
 #mengkonversikan paid date dari format integer ke format date
# Convert 'Paid Date' from integer format to datetime
paid_transaction['Paid Date'] = pd.to_datetime(paid_transaction['Paid Date'], format = '%Y%m%d', errors = 'coerce')
paid_transaction

,Paid Date,Order Number,First Name,Last Name,Full Name,Meta Category,Product Name,Transaction Amount,Seller Discount,Sales Discount,Delivery Fee,Other Discount,GMV,Group
0,2017-07-24,201707240088517,elvride,aries,Elvride Aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,10200.0,9000,0.0,291000,NaN
1,2017-07-01,201707018889790,BASIR,Ninuk,Basir Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,0.0,0,0.0,287800,NaN
2,2017-07-07,201707079264675,Citra,Ardi,Citra Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,700.0,0,0.0,35000,NaN
3,2017-07-20,201707209945714,Dian,Renaldi,Dian Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,5900.0,0,0.0,85000,Group 1
4,2017-07-22,201707220002354,rizal,Tamba,Rizal Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,5600.0,0,0.0,81000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,2017-12-01,201712012704898,Fitrah,gina,Fitrah Gina,Service/ Mokado,"Xtra Combo 12GB, 30hr",333000,300000,2300.0,0,0.0,333000,NaN
11996,2017-12-03,201712032723513,Djebeng,Shinta,Djebeng Shinta,Service/ Mokado,"Xtra Combo 12GB, 30hr",280000,222500,0.0,0,0.0,280000,NaN
11997,2017-12-04,201712042740205,Amik,Elan,Amik Elan,Home/ Food,Kreta - Kripik Tempe Indonesia - Rasa Jomblo d...,150000,81000,4800.0,0,0.0,150000,NaN
11998,2017-12-07,201712072778621,Anna,asih,Anna Asih,Gadget/ Komputer,Samsung Galaxy J5 Pro Garansi Resmi Special Price,475000,400000,0.0,0,0.0,475000,NaN
11999,2017-12-05,201712052746101,nidyah,ayi,Nidyah Ayi,Service/ Mokado,[SERBU 11.12] Share Tea Cocoa Rocksalt & Chees...,475000,400000,20000.0,17000,0.0,458000,NaN

In [ ]:
meta_category_map = {
    'Home/Food' : 'Group 1', 'Sports/Hobi/Otomotif': 'Group 1', 'Fashion': 'Group 1', 'Beauty/Health': 'Group 1',
    'Gadget/Komputer': 'Group 2', 'Elektronik': 'Group 2', 'Service/Mokado': 'Group 2', 'Babies/Kids': 'Group 2'
}
paid_transaction ['Group'] = paid_transaction ['Meta Category'].map(meta_category_map)

pivot_df = paid_transaction.pivot_table(values ='GMV', index=paid_transaction['Paid Date'].dt.to_period('M'), columns ='Group', aggfunc='sum')
paid_transaction

,Paid Date,Order Number,First Name,Last Name,Full Name,Meta Category,Product Name,Transaction Amount,Seller Discount,Sales Discount,Delivery Fee,Other Discount,GMV,Group
0,2017-07-24,201707240088517,elvride,aries,Elvride Aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,10200.0,9000,0.0,291000,NaN
1,2017-07-01,201707018889790,BASIR,Ninuk,Basir Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,0.0,0,0.0,287800,NaN
2,2017-07-07,201707079264675,Citra,Ardi,Citra Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,700.0,0,0.0,35000,NaN
3,2017-07-20,201707209945714,Dian,Renaldi,Dian Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,5900.0,0,0.0,85000,Group 1
4,2017-07-22,201707220002354,rizal,Tamba,Rizal Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,5600.0,0,0.0,81000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,2017-12-01,201712012704898,Fitrah,gina,Fitrah Gina,Service/ Mokado,"Xtra Combo 12GB, 30hr",333000,300000,2300.0,0,0.0,333000,NaN
11996,2017-12-03,201712032723513,Djebeng,Shinta,Djebeng Shinta,Service/ Mokado,"Xtra Combo 12GB, 30hr",280000,222500,0.0,0,0.0,280000,NaN
11997,2017-12-04,201712042740205,Amik,Elan,Amik Elan,Home/ Food,Kreta - Kripik Tempe Indonesia - Rasa Jomblo d...,150000,81000,4800.0,0,0.0,150000,NaN
11998,2017-12-07,201712072778621,Anna,asih,Anna Asih,Gadget/ Komputer,Samsung Galaxy J5 Pro Garansi Resmi Special Price,475000,400000,0.0,0,0.0,475000,NaN
11999,2017-12-05,201712052746101,nidyah,ayi,Nidyah Ayi,Service/ Mokado,[SERBU 11.12] Share Tea Cocoa Rocksalt & Chees...,475000,400000,20000.0,17000,0.0,458000,NaN

In [ ]:
august_data = paid_transaction[paid_transaction['Paid Date'].dt.month == 8]
august_data = august_data[august_data['Paid Date'].dt.year == 2017]


august_gmv = august_data.groupby('Order Number') ['GMV'].sum().idxmax()
seller_with_highest_gmv = seller[seller['Order Number'] == august_gmv]
seller_with_highest_gmv

         Order Number           Seller
1613  201708281180810  MOBILEPULSA APP

In [ ]:
september_data = paid_transaction[(paid_transaction['Paid Date'].dt.month == 9) &
                                  (paid_transaction['Paid Date'].dt.year ==2017) &
                                  (paid_transaction['Meta Category']== 'Fashion')]

most_transactions_seller = september_data['Order Number'].value_counts().idxmax()
seller_with_most_transactions = seller[seller['Order Number']== most_transactions_seller]
seller_with_most_transactions

         Order Number     Seller
1955  201709021277460  duta shop